### ISSUE TITLE
Minimize/Maximise window.

### ISSUE THREAD

**Issue by davidfvj** [aurelienpierre/R-Darktable#28]
Manjaro/Arch/Current git/XFCE
This may be connected to my use of XFCE! I have a panel located across the lower part of the screen which is supposed to function 'intelligently'.
When I run dt the application frame is always 'locked' in the Maximize condition regardless of the tab being used.
With r&dt whenever I move from the darkroom to the lighttable the application frame changes to the Minimize mode.and the lower part of the frame is cut off and cannot be reset to Maximize.
I would like the frame size to remain as Maximize without regard of the tab being used.

**Comment by aurelienpierre** [comment]
R&Dt doesn't do anything to the windowing system and this part of the code has not changed compared to upstream dt. 

The only thing that changed is the title of the main window (darktable -> R&Darktable). So my guess would be your desktop environment may have clever rules referencing "darktable" that don't apply to R&Dt since the window name is not the same.

**Comment by davidvj** [comment]
Thank you for the prompt response .... the problem was on my system ..... inadvertently the desktop had been set with "custom dpi" and as soon as I unchecked that setting the problem was solved.
Thanks again
