### ISSUE TITLE
How about yellow and grey in the color eq?

### ISSUE THREAD

**Issue by RawConvert** [aurelienpierre/R-Darktable#7]
It would be nice to have yellow as a specific colour to make changes to (saturation, hue and brightness), in addition to those already catered for.

It would also be nice to apply a hue to grey areas. (And change brightness too maybe)

**Comment by aurelienpierre** [comment]
> It would be nice to have yellow as a specific colour to make changes to (saturation, hue and brightness), in addition to those already catered for.

Yellow exists only at brightness > 80 %. The GUI colors are drawn at brightness = 50% to avoid being distracting from the main image. Yellow at 50% appears olive-brown. Typical HSV stuff shows yellow because brightness/lightness is not constant over the hue ring. Here we work in perceptual space…

> It would also be nice to apply a hue to grey areas. (And change brightness too maybe)

That's going to be super wonky. Better do it through color balance RGB, it will be more robust (using shadows gain and highlights gain). The main challenge is to have visual effects blend smoothly.

**Comment by RawConvert** [comment]
Re. yellow, I still think Color Eq would be better if you could target specific colours like yellow, even if that means using brightness as well as hue to identify the pixels to be worked on.  I would say this is the functionality that a typical user would like.  However I realise this does not fit with your design.
